kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "mysql.fullname" . }}-{{ .Release.Namespace }}
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate